version: '3.0'

services:

  gobdistribute:
    build: src
    container_name: gobdistribute
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      API_HOST: http://gobapi:8001
    env_file: .env

networks:
  default:
    external:
      name: gob-network
