version: '3.7'

services:

  gobdistribute:
    build: src
    container_name: gobdistribute
    environment:
      MESSAGE_BROKER_ADDRESS: rabbitmq
      API_HOST: http://gobapi:8001
      EXPORT_API_HOST: http://gobexport:8001
    env_file: .env

networks:
  default:
    external: true
    name: gob-network
